name: Deploy React App to Server

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to the Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            ENV=${{ github.event.inputs.environment }}

            # Determine working directory
            if [ "$ENV" == "prod" ]; then
              echo "Deploying to production..."
              WORK_DIR=${{ secrets.PROD_SERVER_DEPLOYMENT_PATH }}
              cd ${{ secrets.PROD_SERVER_DEPLOYMENT_PATH }}
            else
              echo "Deploying to development..."
              WORK_DIR=${{ secrets.DEV_SERVER_DEPLOYMENT_PATH }}
              cd ${{ secrets.DEV_SERVER_DEPLOYMENT_PATH }}
            fi

            echo "working directory"
            echo $WORK_DIR
          
            # Clone if not exists
            if [ ! -d ".git" ]; then
              git clone git@github.com:zoltanpal/pow.palzoltan.net.git .
              git checkout ${{ github.ref_name }}
            fi

            # Pull latest changes
            git fetch origin
            git reset --hard origin/${{ github.ref_name }}
            git clean -fd
            git checkout ${{ github.ref_name }}

            # Set up Node.js environment (assumes Node and npm are installed)
            export PATH=$HOME/.nvm/versions/node/v18.17.1/bin:$PATH

            # Install dependencies and build
            npm install
            npm run build
